import django.contrib.admin as admin
import ML_reviews.models as models

admin.site.register(models.Appliances)
admin.site.register(models.ArtsCraftsAndSewing)
admin.site.register(models.AudioBooks)
admin.site.register(models.Automotive)
admin.site.register(models.BeautyProducts)
admin.site.register(models.Books)
admin.site.register(models.CDsAndVinyl)
admin.site.register(models.CellPhonesAndAccessories)
admin.site.register(models.ClothingShoesAndJewelry)
admin.site.register(models.DigitalMusic)
admin.site.register(models.Electronics)
admin.site.register(models.Fashion)
admin.site.register(models.GiftCards)
admin.site.register(models.GroceryAndGourmetFood)
admin.site.register(models.HomeAndKitchen)
admin.site.register(models.IndustrialAndScientificSupplies)
admin.site.register(models.Magazines)
admin.site.register(models.MoviesAndTV)
admin.site.register(models.MusicalInstruments)
admin.site.register(models.OfficeProducts)
admin.site.register(models.PatioLawnAndGarden)
admin.site.register(models.PetSupplies)
admin.site.register(models.Software)
admin.site.register(models.SportsAndOutdoors)
admin.site.register(models.ToolsAndHomeImprovement)
admin.site.register(models.ToysAndBoardGames)
admin.site.register(models.VideoGames)
admin.site.register(models.Predictors)